version: 2
jobs:
  build:
    docker:
        - image: pterodragon/p_demo
    steps:
        - checkout
        - run: yarn install
        - run: yarn start
          # try if there's a tree command
        - run: tree

