version: 2
jobs:
  build:
    docker:
      - image: pterodragon/p_demo
    steps:
      - checkout
        # try if there's a tree command
      - run: tree

      - setup_remote_docker
      - run:
          name: Start container and verify it's working  # including "$ yarn start"
          command: |
            docker-compose up -d run_app
      - deploy:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t pterodragon/p_demo_deploy:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push pterodragon/p_demo_deploy:$TAG
