version: 2
jobs:
    build:
        docker:
            - image: pterodragon/p_demo
              steps:
                  - checkout
                    # try if there's a tree command
                  - run: tree

                  - setup_remote_docker
                  - run:
                      name: Start container and verify it's working  # including "$ yarn start"
                      command: |
                          docker-compose up
